pr:
  branches:
    include:
      - features/**

resources:
- repo: self

parameters:
  - name: vmImageName
    type: string
    default: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- template: templates/build/app/templates-build-application.yml

- stage: Deploy_Dev
  displayName: 'Deploy to Dev environment'
  dependsOn: Build_Push_Image
  condition: succeeded()

  jobs:
    - deployment: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      environment: test
      variables:
        - group: 'Release'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop
              
              - task: AzureWebApp@1
                displayName: 'Azure App Service Deploy to Dev env'
                inputs:
                  azureSubscription: myARMServiceConnection
                  appType: webAppLinux
                  appName: $(WebAppDev)
                  package: $(Pipeline.Workspace)/drop/