pr:
  branches:
    include:
      - features/**

resources:
- repo: self

parameters:
  - name: vmImageName
    type: string
    default: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
    
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
    
stages:
- stage: Build
  jobs:
    - template: templates/build-app/app/templates-build-application.yml
      parameters:
        vmImageName: $(vmImageName)

- stage: Deploy_Dev
  displayName: 'Deploy to Dev environment'
  dependsOn: Build
  condition: succeeded()

  jobs:
    - deployment: Deploy
      pool:
        vmImage: ${{ parameters.vmImageName }}
      environment: test
      variables:
        - group: 'Release'
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: drop
              
            - task: AzureWebAppContainer@1
              inputs:
                appName: $(WebAppDev)
                azureSubscription: myARMServiceConnection
                containers: 'officetrackingdocker:latest'
                containerCommand:  'java -jar $(Build.SourcesDirectory)/build/libs/office-tracking-0.0.1-SNAPSHOT-plain.jar'
