resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ac125636-b76f-41c6-aecf-a61404c3493c'
  imageRepository: 'officetrackingimage'
  containerRegistry: 'officetrackingcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build_Dev
  displayName: Build an application
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: |
            sudo apt-get update
            sudo apt-get install dos2unix
            dos2unix gradlew
          displayName: Convert the line endings to Unix format
          
        - script: chmod +x gradlew
          displayName: Grant permission for gradlew

        - script: ./gradlew clean build
          displayName: Clean and build new artifact

        - task: PublishBuildArtifacts@1
          displayName: Pubish build artifact
          inputs:
            PathtoPublish: "$(Build.SourcesDirectory)/build/libs/office-tracking-*.jar"
            ArtifactName: drop
            publishLocation: "Container"