pr:
  branches:
    include:
      - features/**

resources:
- repo: self

parameters:
  - name: vmImageName
    type: string
    default: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
    
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
    
stages:
# - stage: Build
#   jobs:
#     - template: templates/build-app/app/templates-build-application.yml
#       parameters:
#         vmImageName: $(vmImageName)

- stage: Deploy_Dev
  displayName: 'Deploy to Dev environment'
  # dependsOn: Build
  # condition: succeeded()

  jobs:
    - deployment: Deploy
      pool:
        vmImage: ${{ parameters.vmImageName }}
      environment: test
      variables:
        - group: 'Release'
      strategy:
        runOnce:
          deploy:
            steps:
              # - download: current
              #   artifact: drop
              
            - task: AzureContainerApps@1
              inputs:
                connectedServiceNameARM: 'myARMServiceConnection'
                imageToDeploy: officetrackingcr.azurecr.io/officetrackingdocker:latest
                resourceGroup: 'azure-devops-tranning-rg'
                containerAppName: 'office-tracking-app-container'
                appSourcePath: '$(System.DefaultWorkingDirectory)'
                # azureSubscription: 'myARMServiceConnection'
                acrName: 'officeTrackingCR'
                acrUsername: 'officeTrackingCR'
                acrPassword: 'S2XfgEPHhKQd0HKvu0twVurf4XXoZFK1ewsQXkHWVY+ACRCnkduf'
                imageToBuild: officetrackingcr.azurecr.io/officetrackingdocker:latest
                dockerfilePath: 'Dockerfile'
