- job: Build_Push_Image
  displayName: 'Build and Push an image to Container Registry'
  dependsOn: Build
  condition: succeeded()

  variables:
    dockerRegistryServiceConnection: myDRServiceConnection
    imageRepository: 'officetrackingimage'
    containerRegistry: 'officetrackingcr.azurecr.io'
    dockerfilePath: '**/Dockerfile'
    nameRepository: 'officetrackingdocker'

  steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(nameRepository)
        Dockerfile: $(dockerfilePath) 